language: php

php:
  - 5.3
  - 5.4

before_script:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script: phpunit